set shell := ["zsh", "-c"]

alias g := gens
alias c := clean
alias r := rebuild
alias d := debug
alias u := flake-update

_default:
    @just -l

# List all generations
gens:
    @echo "Listing home-manager generations"
    @nix-env --list-generations

# Cleans up garbage
clean:
    @echo "Cleaning up unused Nix store items"
    @nix-collect-garbage -d

# Update flake git revision
flake-update:
    @echo "Syncing latest git rev"
    @nix flake update

# Rebuild configuration
[macos]
rebuild:
    @echo "Rebuilding macOS configuration"
    @nix build .#darwinConfigurations.doyeon.system

# Debug 
[macos]
debug:
    @echo "Debugging macOS configuration with --show-trace"
    @nix build .#darwinConfigurations.doyeon.system --show-trace
